In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Preparando a base a ser trabalhada

## Carregando as bases

In [2]:
import os
print(os.getcwd())

D:\docs_mariana\ProjetosGit\averiguacao_cadastral\Analises_Mariana\Analises_modelo

In [3]:
# Load the datasets
df_fam = pd.read_csv('D:/docs_mariana/ProjetosGit/averiguacao_cadastral/Data_balanceado/df_familia_final_balanceado.csv', sep=',', dtype={23: 'str'})

In [4]:
df_fam.head()

,cd_ibge,uf_ibge,regiao_ibge,estrato,classf,id_familia,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_iluminacao_domic_fam,cod_calcamento_domic_fam,cod_familia_indigena_fam,ind_familia_quilombola_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,dias_cadastramento,dias_atualizacao,classe_renda
0,1501402,15,1,2,1,4736936,40.0,1.0,1.0,2.0,...,1.0,3.0,2.0,2.0,0.0,3,550249924045052,3290.0,510,0
1,1304062,13,1,2,3,2562870,119.0,1.0,1.0,4.0,...,1.0,1.0,2.0,2.0,0.0,8,550341300174477,1774.0,101,0
2,2927507,29,2,2,3,1843654,100.0,2.0,1.0,4.0,...,1.0,3.0,2.0,2.0,205.0,2,550080537274825,1966.0,598,0
3,2804607,28,2,2,3,1946851,60.0,2.0,1.0,5.0,...,1.0,3.0,2.0,2.0,0.0,2,550397469252923,812.0,285,0
4,3301009,33,3,2,3,4194650,44.0,1.0,1.0,5.0,...,1.0,1.0,2.0,2.0,0.0,3,550237185178733,5772.0,591,0

In [5]:
# Load the datasets
df_pessoas = pd.read_csv('D:/docs_mariana/ProjetosGit/averiguacao_cadastral/Data_balanceado/df_pessoas_final_balanceado.csv', sep=',', dtype={4: 'str'})

In [6]:
df_pessoas.head()

,id_familia,id_pessoa,cod_sexo_pessoa,idade,cod_parentesco_rf_pessoa,cod_raca_cor_pessoa,cod_local_nascimento_pessoa,cod_certidao_registrada_pessoa,cod_deficiencia_memb,cod_sabe_ler_escrever_memb,...,cod_curso_frequentou_pessoa_memb,cod_ano_serie_frequentou_memb,cod_concluiu_frequentou_memb,cod_trabalhou_memb,cod_afastado_trab_memb,cod_agricultura_trab_memb,cod_principal_trab_memb,cod_trabalho_12_meses_memb,qtd_meses_12_meses_memb,peso.pes
0,4736936,368407,1,17,3,4.0,2.0,1,2,1.0,...,-1.0,-1.0,-1.0,2.0,2.0,-1.0,-1.0,2.0,-1.0,563277363244442
1,4736936,6711807,2,15,3,4.0,2.0,1,2,1.0,...,-1.0,-1.0,-1.0,2.0,2.0,-1.0,-1.0,2.0,-1.0,563277363244442
2,4736936,9879138,2,44,1,4.0,2.0,1,2,2.0,...,-1.0,-1.0,-1.0,1.0,-1.0,2.0,1.0,1.0,9.0,563277363244442
3,2562870,1032042,2,38,1,4.0,1.0,1,2,1.0,...,12.0,-1.0,-1.0,2.0,2.0,-1.0,-1.0,2.0,-1.0,563289238376948
4,2562870,4996944,1,5,3,4.0,1.0,1,1,2.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,563289238376948

In [7]:
# Load the datasets
df_fam_pessoas = pd.read_csv('D:/docs_mariana/ProjetosGit/averiguacao_cadastral/Data_balanceado/df_familia_pessoa_final_balanceado.csv', sep=',', dtype={4: 'str'})

In [8]:
df_fam_pessoas.head()

,cd_ibge,uf_ibge,regiao_ibge,estrato,classf,id_familia,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_curso_frequentou_pessoa_memb,cod_ano_serie_frequentou_memb,cod_concluiu_frequentou_memb,cod_trabalhou_memb,cod_afastado_trab_memb,cod_agricultura_trab_memb,cod_principal_trab_memb,cod_trabalho_12_meses_memb,qtd_meses_12_meses_memb,peso.pes
0,1501402,15,1,2,1,4736936,40.0,1.0,1.0,2.0,...,-1.0,-1.0,-1.0,2.0,2.0,-1.0,-1.0,2.0,-1.0,563277363244442
1,1501402,15,1,2,1,4736936,40.0,1.0,1.0,2.0,...,-1.0,-1.0,-1.0,2.0,2.0,-1.0,-1.0,2.0,-1.0,563277363244442
2,1501402,15,1,2,1,4736936,40.0,1.0,1.0,2.0,...,-1.0,-1.0,-1.0,1.0,-1.0,2.0,1.0,1.0,9.0,563277363244442
3,1304062,13,1,2,3,2562870,119.0,1.0,1.0,4.0,...,12.0,-1.0,-1.0,2.0,2.0,-1.0,-1.0,2.0,-1.0,563289238376948
4,1304062,13,1,2,3,2562870,119.0,1.0,1.0,4.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,563289238376948

In [9]:
# Load the datasets
ideb_2017 = pd.read_csv('D:/docs_mariana/ProjetosGit/averiguacao_cadastral/Analises_Risla/ideb_municipio_publica_2017.csv', sep=',', dtype={4: 'str'})

In [10]:
ideb_2017.head()

   CÃ³digo do MunicÃ­pio  ideb_2017_municipio
0              1100015                  6.2
1              1100023                  5.5
2              1100031                  6.1
3              1100049                  6.3
4              1100056                  6.4

## Fazendo um pipeline para criar as novas features

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
import pandas as pd

# FunÃ§Ã£o para transformar o DataFrame
def extract_rf_features(df):
    # Converter a coluna 'cod_parentesco_rf_pessoa' para inteiro
    df['cod_parentesco_rf_pessoa'] = df['cod_parentesco_rf_pessoa'].astype('int64')
    
    # Filtrar as pessoas que sÃ£o responsÃ¡veis familiares
    df_rf = df[df['cod_parentesco_rf_pessoa'] == 1].copy()
    
    if df_rf.empty:
        print("Aviso: NÃ£o hÃ¡ responsÃ¡veis familiares apÃ³s o filtro.")
        return pd.DataFrame()  # Retorna um DataFrame vazio se nÃ£o houver dados

    # Agrupar pelo 'id_familia' e criar as novas colunas com base nas variÃ¡veis selecionadas
    df_rf = df_rf.groupby('id_familia').agg(
        rf_idade=('idade', 'max'),
        rf_trab_principal=('cod_principal_trab_memb', 'max'),
        rf_com_deficiencia=('cod_deficiencia_memb', 'max'),
        rf_trab_agricultura=('cod_agricultura_trab_memb', 'max'),
        rf_sexo=('cod_sexo_pessoa', 'max'),
        rf_curso_frequentou=('cod_curso_frequentou_pessoa_memb', 'max'),
        rf_curso_frequenta=('cod_curso_frequenta_memb', 'max'),
        rf_trabalhou_semana=('cod_trabalhou_memb', 'max'),
        rf_cor_raca=('cod_raca_cor_pessoa', 'max'),
        rf_concluiu_curso=('cod_concluiu_frequentou_memb', 'max')
    ).reset_index()
    
    return df_rf

# Criar um FunctionTransformer com a funÃ§Ã£o definida
extract_rf_transformer = FunctionTransformer(extract_rf_features)

# Criar o pipeline com a etapa 'features_rf'
pipeline_rf = Pipeline(steps=[
    ('features_rf', extract_rf_transformer)
])

# DataFrame original
df_rf = pipeline_rf.fit_transform(df_pessoas)

# Verificar se o DataFrame transformado contÃ©m dados
df_rf.head()

,id_familia,rf_idade,rf_trab_principal,rf_com_deficiencia,rf_trab_agricultura,rf_sexo,rf_curso_frequentou,rf_curso_frequenta,rf_trabalhou_semana,rf_cor_raca,rf_concluiu_curso
0,105,69,-1.0,2,-1.0,2,4.0,-1.0,2.0,1.0,1.0
1,114,59,1.0,2,2.0,1,4.0,-1.0,1.0,4.0,1.0
2,135,56,-1.0,2,-1.0,2,4.0,-1.0,2.0,1.0,2.0
3,208,67,-1.0,1,-1.0,2,5.0,-1.0,2.0,1.0,2.0
4,217,42,1.0,2,2.0,2,8.0,-1.0,1.0,4.0,1.0

In [12]:
# FunÃ§Ã£o para calcular as porcentagens de trabalho
def extract_trabalho_features(df):
    # Agrupar pelo 'id_familia' e calcular as porcentagens com base nas variÃ¡veis selecionadas
    df_trabalho = df.groupby('id_familia').apply(
        lambda x: pd.Series({
            'pct_extrativista': ((x['cod_agricultura_trab_memb'] == 1) & (x['idade'] >= 18) & (x['idade'] <= 59)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_conta_propria': ((x['cod_principal_trab_memb'] == 1) & (x['idade'] >= 18) & (x['idade'] <= 59)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_trab_rural_temporario': ((x['cod_principal_trab_memb'] == 2) & (x['idade'] >= 18) & (x['idade'] <= 59)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_empregado_sem_carteira': ((x['cod_principal_trab_memb'] == 3) & (x['idade'] >= 18) & (x['idade'] <= 59)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_empregado_com_carteira': ((x['cod_principal_trab_memb'] == 4) & (x['idade'] >= 18) & (x['idade'] <= 59)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_trab_domestico_sem_carteira': ((x['cod_principal_trab_memb'] == 5) & (x['idade'] >= 18) & (x['idade'] <= 59)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_militar_servidor': ((x['cod_principal_trab_memb'] == 8) & (x['idade'] >= 18) & (x['idade'] <= 59)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_trabalho_12meses_adulto': ((x['cod_trabalho_12_meses_memb'] == 1) & (x['idade'] >= 18) & (x['idade'] <= 59)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_trabalho_12meses_idoso': ((x['cod_trabalho_12_meses_memb'] == 1) & (x['idade'] >= 60)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_trabalho_12meses_crianca': ((x['cod_trabalho_12_meses_memb'] == 1) & (x['idade'] < 18)).sum() / x['qtde_pessoas'].iloc[0],
        })
    ).reset_index()
    
    return df_trabalho

# Criar um FunctionTransformer com a funÃ§Ã£o definida
extract_trabalho_transformer = FunctionTransformer(extract_trabalho_features)

# Criar o pipeline com a etapa 'features_trabalho'
pipeline_trabalho = Pipeline(steps=[
    ('features_trabalho', extract_trabalho_transformer)
])

# DataFrame original
df_trabalho = pipeline_trabalho.fit_transform(df_fam_pessoas)

# Verificar se o DataFrame transformado contÃ©m dados
df_trabalho.head()

,id_familia,pct_extrativista,pct_conta_propria,pct_trab_rural_temporario,pct_empregado_sem_carteira,pct_empregado_com_carteira,pct_trab_domestico_sem_carteira,pct_militar_servidor,pct_trabalho_12meses_adulto,pct_trabalho_12meses_idoso,pct_trabalho_12meses_crianca
0,105,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
1,114,0.0,1.00,0.0,0.0,0.000000,0.0,0.0,1.000000,0.0,0.0
2,135,0.0,0.00,0.0,0.0,0.333333,0.0,0.0,0.333333,0.0,0.0
3,208,0.0,0.00,0.0,0.0,0.200000,0.0,0.0,0.400000,0.0,0.0
4,217,0.0,0.25,0.0,0.0,0.000000,0.0,0.0,0.500000,0.0,0.0

In [13]:
# FunÃ§Ã£o para extrair as features de escolaridade
def extract_escola_features(df):
    # Agrupar pelo 'id_familia' e calcular as porcentagens relacionadas Ã  escolaridade
    df_escola = df.groupby('id_familia').apply(
        lambda x: pd.Series({
            'pct_nao_alfabetizados': ((x['cod_sabe_ler_escrever_memb'] == 2) & (x['idade'] >= 10)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_n_freq_escola': ((x['ind_frequenta_escola_memb'] == 3) & (x['idade'] >= 4) & (x['idade'] <= 17)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_freq_publica': ((x['ind_frequenta_escola_memb'] == 1) & (x['idade'] >= 4) & (x['idade'] <= 17)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_freq_particular': ((x['ind_frequenta_escola_memb'] == 2) & (x['idade'] >= 4) & (x['idade'] <= 17)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_adulto_nunca_freq_escola': ((x['ind_frequenta_escola_memb'] == 4) & (x['idade'] >= 18)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_escolar_nunca_freq_escola': ((x['ind_frequenta_escola_memb'] == 4) & (x['idade'] >= 4) & (x['idade'] <= 17)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_freq_creche': ((x['cod_curso_frequenta_memb'] == 1) & (x['idade'] < 4)).sum() / x['qtde_pessoas'].iloc[0],
        })
    ).reset_index()
    
    return df_escola

# Criar um FunctionTransformer com a funÃ§Ã£o definida
extract_escola_transformer = FunctionTransformer(extract_escola_features)

# Criar o pipeline com a etapa 'features_escola'
pipeline_escola = Pipeline(steps=[
    ('features_escola', extract_escola_transformer)
])

# DataFrame original
df_escola = pipeline_escola.fit_transform(df_fam_pessoas)

# Verificar se o DataFrame transformado contÃ©m dados
df_escola.head()

,id_familia,pct_nao_alfabetizados,pct_n_freq_escola,pct_freq_publica,pct_freq_particular,pct_adulto_nunca_freq_escola,pct_escolar_nunca_freq_escola,pct_freq_creche
0,105,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
1,114,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
2,135,0.333333,0.0,0.0,0.0,0.333333,0.0,0.0
3,208,0.000000,0.0,0.2,0.0,0.000000,0.0,0.0
4,217,0.000000,0.0,0.5,0.0,0.000000,0.0,0.0

In [14]:
# FunÃ§Ã£o para verificar a existÃªncia da caracterÃ­stica
def verifica_caracteristica(x, condicao):
    return 1 if condicao.any() else 0

# FunÃ§Ã£o para extrair as features de composiÃ§Ã£o
def extract_composicao_features(df):
    df_composicao = df.groupby('id_familia').apply(
        lambda x: pd.Series({
            'pct_idosos': (x['idade'] >= 60).sum() / x['qtde_pessoas'].iloc[0],
            'pct_deficientes': (x['cod_deficiencia_memb'] == 1).sum() / x['qtde_pessoas'].iloc[0],
            'pct_1_infancia': (x['idade'] <= 6).sum() / x['qtde_pessoas'].iloc[0],
            'pct_adulto': ((x['idade'] >= 18) & (x['idade'] < 60)).sum() / x['qtde_pessoas'].iloc[0],
            'pct_crianca_adolescente': ((x['idade'] > 6) & (x['idade'] <= 17)).sum() / x['qtde_pessoas'].iloc[0],
            'fam_gpte': verifica_caracteristica(x, (x['ind_parc_mds_fam'] != 0) | 
                                                 (x['cod_familia_indigena_fam'] == 1) | 
                                                 (x['ind_familia_quilombola_fam'] == 1))
        })
    ).reset_index()
    
    return df_composicao

# Criar um FunctionTransformer com a funÃ§Ã£o definida
extract_composicao_transformer = FunctionTransformer(extract_composicao_features)

# Criar o pipeline com a etapa 'features_composicao'
pipeline_composicao = Pipeline(steps=[
    ('features_composicao', extract_composicao_transformer)
])

# DataFrame original
df_composicao = pipeline_composicao.fit_transform(df_fam_pessoas)

# Verificar se o DataFrame transformado contÃ©m dados
df_composicao.head()

,id_familia,pct_idosos,pct_deficientes,pct_1_infancia,pct_adulto,pct_crianca_adolescente,fam_gpte
0,105,1.000000,0.000000,0.00,0.000000,0.00,0.0
1,114,0.000000,0.000000,0.00,1.000000,0.00,0.0
2,135,0.333333,0.333333,0.00,0.666667,0.00,0.0
3,208,0.400000,0.200000,0.00,0.400000,0.20,0.0
4,217,0.000000,0.000000,0.25,0.500000,0.25,0.0

In [15]:
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

# Criar um transformador personalizado
class FeaturesIdebTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, ideb_data):
        self.ideb_data = ideb_data

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        # Realizar o merge com a base de dados do IDEB
        df_fam_ideb = X.merge(
            self.ideb_data,
            left_on='cd_ibge',
            right_on='CÃ³digo do MunicÃ­pio',
            how='left'
        )
        
        # Remover a coluna 'CÃ³digo do MunicÃ­pio'
        df_fam_ideb = df_fam_ideb.drop('CÃ³digo do MunicÃ­pio', axis=1)

        # Preencher os valores ausentes de 'ideb_2017_municipio' com -1
        df_fam_ideb['ideb_2017_municipio'].fillna(-1, inplace=True)
        
        # Selecionar apenas as colunas desejadas
        df_fam_ideb = df_fam_ideb[['id_familia', 'ideb_2017_municipio']]
        
        return df_fam_ideb

# Criar o pipeline
pipeline_ideb = Pipeline(steps=[
    ('features_ideb', FeaturesIdebTransformer(ideb_2017))
])

# Aplicar o pipeline ao DataFrame df_fam
df_ideb = pipeline_ideb.fit_transform(df_fam)

# Visualizar o resultado
print(df_ideb.head())

   id_familia  ideb_2017_municipio
0     4736936                  4.8
1     2562870                  4.6
2     1843654                  4.0
3     1946851                  4.2
4     4194650                  4.6

In [16]:
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline, FeatureUnion

class FeaturesDomicilioTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        # Remover as colunas indesejadas do DataFrame
        return X.drop(columns=[
            'regiao_ibge', 'estrato', 'vlr_renda_media_fam',
            'cod_especie_domic_fam', 'qtd_comodos_dormitorio_fam',
            'cod_material_domic_fam', 'cod_agua_canalizada_fam',
            'cod_abaste_agua_domic_fam', 'cod_banheiro_domic_fam',
            'cod_escoa_sanitario_domic_fam', 'cod_destino_lixo_domic_fam',
            'cod_calcamento_domic_fam', 'peso.fam'
        ])

# Criar o pipeline
pipeline_domicilio = Pipeline([
    ('features_transformer', FeaturesDomicilioTransformer())
])

# Supondo que df_fam jÃ¡ tenha sido carregado anteriormente
# Aplicar o pipeline ao DataFrame df_fam
df_domicilio = pipeline_domicilio.fit_transform(df_fam)

# Exibir as primeiras linhas do novo DataFrame df_domicilio
df_domicilio.head()

,cd_ibge,uf_ibge,classf,id_familia,cod_local_domic_fam,qtd_comodos_domic_fam,cod_material_piso_fam,cod_iluminacao_domic_fam,cod_familia_indigena_fam,ind_familia_quilombola_fam,ind_parc_mds_fam,qtde_pessoas,dias_cadastramento,dias_atualizacao,classe_renda
0,1501402,15,1,4736936,1.0,2.0,2.0,1.0,2.0,2.0,0.0,3,3290.0,510,0
1,1304062,13,3,2562870,1.0,4.0,2.0,1.0,2.0,2.0,0.0,8,1774.0,101,0
2,2927507,29,3,1843654,2.0,4.0,2.0,1.0,2.0,2.0,205.0,2,1966.0,598,0
3,2804607,28,3,1946851,2.0,5.0,2.0,1.0,2.0,2.0,0.0,2,812.0,285,0
4,3301009,33,3,4194650,1.0,5.0,5.0,1.0,2.0,2.0,0.0,3,5772.0,591,0

In [17]:
import pandas as pd

# DataFrames dos pipelines sejam:
# df_rf, df_trabalho, df_escola, df_composicao, df_ideb, df_domicilio

# Realizar merge dos DataFrames
# Primeiro, iniciamos com df_rf
df_modelo = df_rf

# Merge com df_trabalho
df_modelo = df_modelo.merge(df_trabalho, on='id_familia', how='left')

# Merge com df_escola
df_modelo = df_modelo.merge(df_escola, on='id_familia', how='left')

# Merge com df_composicao
df_modelo = df_modelo.merge(df_composicao, on='id_familia', how='left')

# Merge com df_ideb
df_modelo = df_modelo.merge(df_ideb, on='id_familia', how='left')

# Merge com df_domicilio
df_modelo = df_modelo.merge(df_domicilio, on='id_familia', how='left')

# Remover duplicatas, se houver
df_modelo = df_modelo.drop_duplicates(subset=['id_familia'])

# Resetar o Ã­ndice, se necessÃ¡rio
df_modelo.reset_index(drop=True, inplace=True)

# Verificar se o DataFrame final contÃ©m dados
df_modelo.head()

,id_familia,rf_idade,rf_trab_principal,rf_com_deficiencia,rf_trab_agricultura,rf_sexo,rf_curso_frequentou,rf_curso_frequenta,rf_trabalhou_semana,rf_cor_raca,...,qtd_comodos_domic_fam,cod_material_piso_fam,cod_iluminacao_domic_fam,cod_familia_indigena_fam,ind_familia_quilombola_fam,ind_parc_mds_fam,qtde_pessoas,dias_cadastramento,dias_atualizacao,classe_renda
0,105,69,-1.0,2,-1.0,2,4.0,-1.0,2.0,1.0,...,4.0,5.0,1.0,2.0,2.0,0.0,1,2518.0,493,2
1,114,59,1.0,2,2.0,1,4.0,-1.0,1.0,4.0,...,3.0,5.0,1.0,2.0,2.0,0.0,1,224.0,224,2
2,135,56,-1.0,2,-1.0,2,4.0,-1.0,2.0,1.0,...,5.0,5.0,1.0,2.0,2.0,0.0,3,203.0,203,2
3,208,67,-1.0,1,-1.0,2,5.0,-1.0,2.0,1.0,...,6.0,5.0,1.0,2.0,2.0,0.0,5,1650.0,377,2
4,217,42,1.0,2,2.0,2,8.0,-1.0,1.0,4.0,...,6.0,5.0,1.0,2.0,2.0,0.0,4,194.0,194,0

In [18]:
df_modelo.shape

(96792, 49)

In [19]:
df_modelo.columns

Index(['id_familia', 'rf_idade', 'rf_trab_principal', 'rf_com_deficiencia',
       'rf_trab_agricultura', 'rf_sexo', 'rf_curso_frequentou',
       'rf_curso_frequenta', 'rf_trabalhou_semana', 'rf_cor_raca',
       'rf_concluiu_curso', 'pct_extrativista', 'pct_conta_propria',
       'pct_trab_rural_temporario', 'pct_empregado_sem_carteira',
       'pct_empregado_com_carteira', 'pct_trab_domestico_sem_carteira',
       'pct_militar_servidor', 'pct_trabalho_12meses_adulto',
       'pct_trabalho_12meses_idoso', 'pct_trabalho_12meses_crianca',
       'pct_nao_alfabetizados', 'pct_n_freq_escola', 'pct_freq_publica',
       'pct_freq_particular', 'pct_adulto_nunca_freq_escola',
       'pct_escolar_nunca_freq_escola', 'pct_freq_creche', 'pct_idosos',
       'pct_deficientes', 'pct_1_infancia', 'pct_adulto',
       'pct_crianca_adolescente', 'fam_gpte', 'ideb_2017_municipio', 'cd_ibge',
       'uf_ibge', 'classf', 'cod_local_domic_fam', 'qtd_comodos_domic_fam',
       'cod_material_piso_fam', 'cod_iluminacao_domic_fam',
       'cod_familia_indigena_fam', 'ind_familia_quilombola_fam',
       'ind_parc_mds_fam', 'qtde_pessoas', 'dias_cadastramento',
       'dias_atualizacao', 'classe_renda'],
      dtype='object')

In [20]:
df_modelo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96792 entries, 0 to 96791
Data columns (total 49 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_familia                       96792 non-null  int64
 1   rf_idade                         96792 non-null  int64
 2   rf_trab_principal                96792 non-null  float64
 3   rf_com_deficiencia               96792 non-null  int64
 4   rf_trab_agricultura              96792 non-null  float64
 5   rf_sexo                          96792 non-null  int64
 6   rf_curso_frequentou              96792 non-null  float64
 7   rf_curso_frequenta               96792 non-null  float64
 8   rf_trabalhou_semana              96792 non-null  float64
 9   rf_cor_raca                      96792 non-null  float64
 10  rf_concluiu_curso                96792 non-null  float64
 11  pct_extrativista                 96792 non-null  float64
 12  pct_conta_propria                96792 non-null  float64
 13  pct_trab_rural_temporario        96792 non-null  float64
 14  pct_empregado_sem_carteira       96792 non-null  float64
 15  pct_empregado_com_carteira       96792 non-null  float64
 16  pct_trab_domestico_sem_carteira  96792 non-null  float64
 17  pct_militar_servidor             96792 non-null  float64
 18  pct_trabalho_12meses_adulto      96792 non-null  float64
 19  pct_trabalho_12meses_idoso       96792 non-null  float64
 20  pct_trabalho_12meses_crianca     96792 non-null  float64
 21  pct_nao_alfabetizados            96792 non-null  float64
 22  pct_n_freq_escola                96792 non-null  float64
 23  pct_freq_publica                 96792 non-null  float64
 24  pct_freq_particular              96792 non-null  float64
 25  pct_adulto_nunca_freq_escola     96792 non-null  float64
 26  pct_escolar_nunca_freq_escola    96792 non-null  float64
 27  pct_freq_creche                  96792 non-null  float64
 28  pct_idosos                       96792 non-null  float64
 29  pct_deficientes                  96792 non-null  float64
 30  pct_1_infancia                   96792 non-null  float64
 31  pct_adulto                       96792 non-null  float64
 32  pct_crianca_adolescente          96792 non-null  float64
 33  fam_gpte                         96792 non-null  float64
 34  ideb_2017_municipio              96792 non-null  float64
 35  cd_ibge                          96792 non-null  int64
 36  uf_ibge                          96792 non-null  int64
 37  classf                           96792 non-null  int64
 38  cod_local_domic_fam              96792 non-null  float64
 39  qtd_comodos_domic_fam            96792 non-null  float64
 40  cod_material_piso_fam            96792 non-null  float64
 41  cod_iluminacao_domic_fam         96792 non-null  float64
 42  cod_familia_indigena_fam         96792 non-null  float64
 43  ind_familia_quilombola_fam       96792 non-null  float64
 44  ind_parc_mds_fam                 96792 non-null  float64
 45  qtde_pessoas                     96792 non-null  object
 46  dias_cadastramento               96791 non-null  float64
 47  dias_atualizacao                 96792 non-null  int64
 48  classe_renda                     96792 non-null  int64
dtypes: float64(39), int64(9), object(1)
memory usage: 36.2+ MB

In [21]:
df_modelo.isnull().sum().sum()

1

In [22]:
df_modelo_final = df_modelo.dropna()

In [23]:
df_modelo_final.isnull().sum().sum()

0

In [24]:
df_modelo_final.shape

(96791, 49)

In [28]:
# Liste todos os arquivos e pastas no diretÃ³rio atual
print(os.listdir(os.getcwd()))

['.ipynb_checkpoints', 'catboost_info', 'catboost_tmp', 'Consolidando_resultados.ipynb', 'Final_Modelos_df_balanceado_ordinal.ipynb', 'Final_Modelo_df_balanceado_onehotencoder.ipynb', 'Final_Modelo_df_balanceado_onehotencoder_catboost.ipynb', 'Final_Modelo_df_nao_balanceado_onehotencoder_catboost_balanceado.ipynb', 'Final_Modelo_df_nao_balanceado_onehotencoder_RandomForest.ipynb', 'Final_Modelo_df_nao_balanceado_onehotencoder_simples_ajustado.ipynb', 'Final_Modelo_df_nao_balanceado_onehotencoder_simples_balanceado.ipynb', 'Modelos_df_balanceado_dummies.ipynb', 'Modelos_df_balanceado_michela.ipynb', 'Modelos_df_balanceado_padrao.ipynb', 'resultados_modelos.csv']

In [26]:
# Salvar o DataFrame final em um arquivo, se necessÃ¡rio
df_modelo_final.to_csv('Data_modelo/df_modelo_final.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'Data_modelo'

# Como chamar o modelo apÃ³s preparar a base
# pipeline_1.predict(X do df_modelo)