In [4]:
import pandas as pd

In [5]:
# Carregar o dataframe
df_pessoas_final_2 = pd.read_csv('../Data/df_pessoas_final_2.csv')

In [6]:
df_pessoas_final_2.head()

,id_familia,id_pessoa,cod_sexo_pessoa,idade,cod_parentesco_rf_pessoa,cod_raca_cor_pessoa,cod_local_nascimento_pessoa,cod_certidao_registrada_pessoa,cod_deficiencia_memb,cod_sabe_ler_escrever_memb,...,cod_curso_frequentou_pessoa_memb,cod_ano_serie_frequentou_memb,cod_concluiu_frequentou_memb,cod_trabalhou_memb,cod_afastado_trab_memb,cod_agricultura_trab_memb,cod_principal_trab_memb,cod_trabalho_12_meses_memb,qtd_meses_12_meses_memb,peso.pes
0,2297048,5080082,2,24,1,4.0,2.0,1,2,1.0,...,5.0,5.0,2.0,2.0,2.0,-1.0,-1.0,2.0,-1.0,563253083138481
1,2297048,6871939,2,5,3,4.0,2.0,1,2,2.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,563253083138481
2,2297048,12839729,1,2,3,4.0,2.0,1,2,2.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,563253083138481
3,697587,4991136,1,84,1,4.0,1.0,1,2,2.0,...,-1.0,-1.0,-1.0,2.0,2.0,-1.0,-1.0,2.0,-1.0,563276925444753
4,3807697,1628136,2,24,1,4.0,2.0,1,2,1.0,...,-1.0,-1.0,-1.0,2.0,2.0,-1.0,-1.0,2.0,-1.0,563276393161791

In [7]:
# Incluindo a coluna calsse_renda no df_pessoas_final
# Carregar o arquivo CSV 
df_familia_final_2 = pd.read_csv('../Data/df_familia_final_2.csv')

In [8]:
df_familia_final_2.head()

,cd_ibge,uf_ibge,regiao_ibge,estrato,classf,id_familia,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_iluminacao_domic_fam,cod_calcamento_domic_fam,cod_familia_indigena_fam,ind_familia_quilombola_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,dias_cadastramento,dias_atualizacao,classe_renda
0,2708501,27,2,2,3,2297048,40.0,1.0,1.0,5.0,...,1.0,2.0,2.0,2.0,0.0,3,550128323898416,2478.0,382,0.0
1,2516607,25,2,1,3,697587,937.0,2.0,1.0,6.0,...,1.0,3.0,2.0,2.0,0.0,1,550245146328323,483.0,483,2.0
2,2312908,23,2,2,3,3807697,66.0,1.0,1.0,4.0,...,1.0,2.0,2.0,2.0,0.0,3,550245146328323,1118.0,144,0.0
3,2911709,29,2,2,3,3322305,636.0,1.0,1.0,4.0,...,1.0,1.0,2.0,2.0,0.0,3,550295410213721,242.0,238,2.0
4,3168705,31,3,2,2,1891054,200.0,1.0,1.0,3.0,...,1.0,1.0,2.0,2.0,0.0,3,550245146328323,279.0,279,1.0

In [ ]:
# Realizar o merge entre df_pessoas_final e df_familia_final para adicionar a coluna 'classe_renda'
# Usando a coluna 'id_familia' como chave para associar
df_pessoas_final_2 = df_pessoas_final_2.merge(
    df_familia_final_2[['id_familia', 'classe_renda']],
    on='id_familia',
    how='left'
)

# Verificar se o merge foi realizado corretamente e se a coluna 'classe_renda' estÃ¡ presente
print(f"NÃºmero de pessoas no dataframe final: {df_pessoas_final_2.shape[0]}")
print(f"NÃºmero de valores nulos na coluna 'classe_renda': {df_pessoas_final_2['classe_renda'].isnull().sum()}")
df_pessoas_final.head()